### ISSUE TITLE
Lost "G"

### ISSUE THREAD

**Issue by Bodhi1satva** [bsorrentino/keychain-ios-app#22]
I've been using Keychain for some time now and it's been terrific for helping me keep track of my sign on info for way too many sites and I'm grateful! However, I just realized that any of the stuff I thought I had added to my list that had the letter G as the first letter in the title hasn't been saved or at least it's not keeping them like for Google or GitHub. Don't understand but maybe you can help me out here. Plus I can't seem to find where or how I can change my master password. 
Thanks

**Comment by bsorrentino** [comment]
close due inactivity
